### ISSUE TITLE
Relax c++17 to c++14

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/libuast#51]
Currently, tests are built using `-std=c++17`. This is *very* hardcore. Many people are not able to have that much fresh compiler; actually, according to the issues they file in my own repos, the majority have just switched to CentOS7 or are using Ubuntu 16.04 and can only compile c++11/14.

`examples/example.cc` contains `#include <optional>` which [appears in c++17](http://en.cppreference.com/w/cpp/utility/optional). As well as `tests/mock_node.h` and probably others. This is the only feature which is used from c++17 as far as I see.

Please, show your cutting edge mercy :)

**Comment by vmarkovtsev** [comment]
Besides, the README does not mention that we have to use a C++17-capable compiler anywhere. "Build/Install C API" instructions are broken on current *stock* Ubuntu LTS and CentOS.

Another workaround is to build the examples and tests optionally: the main code is C99 and not C11 hehe.

**Comment by abeaumont** [comment]
Yes, we're quite bleeding edge (we don't support Go versions provided by CentOS7 or Ubuntu 16.04 either), but it would be better to not require them to build `libuast` (it shouldn't since it's only for testing and examples and it could be made optional as you say). I will either make them optional or just drop optional usage.
