### ISSUE TITLE
Memory leak in LastError()

### ISSUE THREAD

**Issue by vmarkovtsev** [bblfsh/libuast#61]
`LastError()` calls `strndup()` which calls `malloc()` inside, and then we throw `std::runtime_error` with it. This either converts to `std::string` or eats `const char*` which end users for sure do not expect to `free(what())`. To spice this strawberry, the error handling itself is currently an anti-pattern (global variable, not thread safe, etc.).

**Comment by vmarkovtsev** [comment]
My suggestions:

1. For sure remove the global error variable. `Error()` accepts `void *ctx` which should be used as the key in the global `unordered_map` or smth.
2. Drop these `strdup()`-s and switch to strings.

**Comment by abeaumont** [comment]
Thanks for reporting @vmarkovtsev. When migrating to exceptions internally we added the message to the exception, which is causing the leak. I think this is not needed since the exceptions are internal while `LastError` is a public API function, thus the exception handling does not need to access these error messages. So may suggestion would be to remove the usage of LastError in the exception throw (the buffer could directly be used internally). What do you think @juanjux? Could you take care of this?

OTOH, strings cannot be used for a C API. Using a global map instead of a single global variable is a design tradeoff.

**Comment by juanjux** [comment]
The error handling is certainly anti pattern; it's because the internal code is halfway migrated between the original pure C implementation and a pure C++ one (see #56), except for the public C API. We migrate a little more with every new feature but probably we should plan finishing the migration as a separate task on a sprint.

The runtime_errors certainly doesn't need to call LastError().

**Comment by abeaumont** [comment]
I think the error handling is orthogonal to C++ migration. The C++ migration has caused the leak but doesn't affect error handling. Error handling requires heap memory due to the API being C. The global variable is used because it's currently the simplest method to achieve it. `libuast` is not currently thread-safe, so that's not a problem at this point.
